# Use NFC pads as GPIOS
CONFIG_NFCT_PINS_AS_GPIOS=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y

# Enable the display
CONFIG_ZMK_DISPLAY=y

# Name of the board
CONFIG_ZMK_KEYBOARD_NAME="mgr8's Corne"

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
