name: Build ZMK Config
on:
  workflow_dispatch: # can be triggered manually
  push: # automatically run on changes to following paths
    paths:
      - "boards/shields/corne_xiao_v2/*.keymap"
      - "boards/shields/corne_xiao_v2/*.dtsi"
      - "dts/layouts/corne_xiao/*.dtsi"
      - "keymap_drawer.config.yaml"
      - "config/*.conf"
      # - 'boards/*/*/*.keymap'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
