name: Build ZMK Config
on:
  workflow_dispatch: # can be triggered manually
  push: # automatically run on changes to following paths
    paths:
      - "dts/layouts/corne_xiao/*.dtsi"
      - "config/*.conf"
      - "config/*.keymap"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
